import "./globals.css";
import Navbar from "../component/Navbar";
import StarWarp from "../component/StarFieldCanvas";
import CustomCursor from "../component/CustomCursor";
import { AuthProvider } from "../component/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
        <title>AstroNova</title>
      </head>
      <body>
        <AuthProvider>
          <CustomCursor />
          <Navbar />
          <StarWarp />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
